sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "D61zXfiLh2wwVJAlKujmteEOftUk/CSFgMDRvUwTij4fJ9mGz5ACnnlw717BuehIIOxyUpKceJwYMm8e965Vk03Piuhcur44mFGmXFNu3LToNWaSiYPpA1ryGhvNoXLdiumn9RhFM8fOqlqo2WyIBIcpv5EmLIYm443yRZ5YYABuYhWuCgUVc7f5GYvZOs1jdSWDLTNsJtznULjzJMw97TlTHf/z/PbH35OM3TPcwPGgnwCi3uAvd9SrYOPvWOQaCePFcqSq6OUKmWyYgsjBGXJCMOESNqVLgJjkOZEijuRNqu82NA61ls3wqSX9tWdA0XO3ogCZTL5DCX0QYDwsnsuycEELA9TmCXZoB3oQFfYYkxhRrIOYjV9zy4lU8xAOuA3A4KaMfA5/Tx/8CoWOnFe67AHmT5vW3Ki2RYF1zmdSq4dnKTZ5rkAMFyjFcNz/LxCMcQ/wnacRZlR+b0pYRSlnbMk4F4ikSAC9EgfGiSGVessddtS4Y08xKWefKG4gXrFb2Jli38JzoSOo6Peh+h2gwApQegp7Yv2N7TA/frG9Dppuy+1DvO6BDNNE2BHoakyF9/4LNpXTjIVBOuPOtLICiGalZmHUNcg1hk8/27mGZqNMKEqLtiw/bgt07caFXxfmEOK4JhXt5lT8B/8NyqQaROxTMpdcMq4WJ2RIsTg="


addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "lgG+TMvMZsfsiz8GtWriFAjc6P581cKHAjtbGHlqeNtf4wMyzmuOaIrPR8H8aVbHusRq4HwYIA22IGdFQNF7gMEbb4LEC9k9t9avDT7/L0BgqITm7jMvEQgpUahSsh299siAsrIqiA+ZdXTf+3lr0vU3K+PllXwmdPH/TmJDrnSgpJzzAthcW91xMUywJbmT8ojtra71/ROeu5560KNxrP8+yufsviA8OyB+nZhutsPePoYqlpBZwaypYmh4pvQAdDSDtFoCROgRzgLVFWaCL0o5WTwip2k5Hke+WXvPGRG+ltR87FTW/RtJmjA9h9qsofCBhNcf+S/bTDsjPUJezOhVQe1hLZAQaXig6E0bUQRoukQVEwI76l6DRmS9rTb6IwfUp6GK5gbiS4c0QiB34lRHPQ2dVf7F6AFCk2DOisYD6vEE3uCxLelUXJ6DZOfKLIzqs1z3Q7Xfnp+uCePpEticJo83wJgLvqr/bHULnTpKoL+dDW5/VJ1ROEhgskJMx2+Noa6jOaQbD1d5lBS9z4lV6vaQCXpjEWkkIPz6uIvIiB5R71bBrPOePqOJjGWQU/pCBO8U4ZS/XzHReZwkQkLXra7jWYR7NvOTa4/iC+gTKgq5ZJk/fU/iA+mg7OUNHahXfXWONlcNr/tgS/s9tc93ZBcw5jV8A2BuSl2EWXw="

  coverity_scan:
    project:
      name: jameshnsears/pytest-docker-py
      version: HEAD
      description: pytest-docker-py
    notification_email: james.hn.sears@gmail.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan


services:
  - docker

cache:
  directories:
  - $HOME/.sonar/cache

language: python

python:
  - "3.6"

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - export PYTHONPATH=src:test:$PYTHONPATH
  - flake8 src test
  - pylint --rcfile=setup.cfg src test -r n > pylint-report.txt 2>&1 || true

script:
  - pytest -s --cov-report term-missing --cov . test/unit
  - mkdir coverage
  - mv .coverage coverage/.coverage.0

  - pip install git+https://github.com/jameshnsears/pytest-docker-py@master
  - pytest -s --cov-report term-missing --cov . test
  - mv .coverage coverage/.coverage.1
  - cd coverage
  - coverage combine
  - coverage xml -i
  - mv .coverage coverage.xml ..
  - cd ..

after_success:
  - COVERALLS_REPO_TOKEN=sF7rXEmZZcdOPJmDWQwjbYoJF2ct8BjPi coveralls
  - sonar-scanner

after_failure:
  - docker images
  - docker ps -a
